export const LABELS = [
  { id: "hot-lead", name: "Hot Lead", color: "#EF4444", bg: "#FEE2E2", description: "High-value opportunity" },
  { id: "follow-up", name: "Follow Up", color: "#F59E0B", bg: "#FEF3C7", description: "Needs response soon" },
  { id: "client", name: "Client", color: "#10B981", bg: "#D1FAE5", description: "Existing customer" },
  { id: "partner", name: "Partner", color: "#0066FF", bg: "#DBEAFE", description: "Business partnership" },
  { id: "investor", name: "Investor", color: "#8B5CF6", bg: "#EDE9FE", description: "Funding or VC contact" },
  { id: "hiring", name: "Hiring", color: "#14B8A6", bg: "#CCFBF1", description: "Recruitment conversation" },
  { id: "prospect", name: "Prospect", color: "#0066FF", bg: "#DBEAFE", description: "Potential future lead" },
  { id: "community", name: "Community", color: "#3B82F6", bg: "#DBEAFE", description: "Friendly network contact" },
  { id: "low-priority", name: "Low Priority", color: "#9CA3AF", bg: "#F3F4F6", description: "Not urgent" },
  { id: "spam", name: "Spam", color: "#9CA3AF", bg: "#F3F4F6", description: "Unwanted message" },
];

export const AI_SUGGESTIONS = [
  "This is the first ai message suggestion, choose it or check others",
  "This is the second ai message suggestion, choose it or check others",
  "This is the third ai message suggestion, choose it or check others, you can also reload",
];

export const CONVERSATIONS = [
  {
    id: 1,
    name: "Bernard Yen",
    title: "HR Manager, NovaTech",
    avatar: null,
    avatarBg: "#F97316",
    time: "2h ago",
    preview: "Hi Grace, I saw your profile on Linkedin and I was impressed with your Background in UX design...",
    labels: ["hiring"],
    unread: true,
    mailbox: "inbox",
    contact: {
      role: "HR Manager at NovaTech",
      location: "Sans Francisco, USA",
      email: "bernardyen@novatech.com",
      linkedin: "linkedin.com/in/Bernard-yen-hr",
    },
    contactLabels: ["Recruiting", "Fintech"],
    note: "Interested in senior candidates for product design role . Prefers morning meeting",
    aiSummary:
      "Bernard is recruiting for a lead senior product designer. You\u2019ve expressed interest and she suggested a meeting on Friday at 10am PST.",
    messages: [
      { id: 1, sender: "them", text: "Hi Grace, I saw your profile on Linkedin and I was impressed with your background in UX design. Your experience designing intuitive dashboards and productivity tools caught my attention.", time: "10:14am", date: "Monday, March 16" },
      { id: 2, sender: "them", text: "Are you open to exploring new opportunities at the moment?", time: "10:20am", date: "Monday, March 16" },
      { id: 3, sender: "me", text: "Hi Daniel, thank you for reaching out and for the kind words about my work. I\u2019m always open to learning about interesting opportunities, especially roles where I can work on impactful product experiences. Could you tell me a bit more about the role and the team?", time: "11:25am", date: "Monday, March 16" },
      { id: 4, sender: "them", text: "Absolutely. We\u2019re currently expanding our product team at NovaTech Solutions and looking for a Senior UX Designer who can help us improve the experience of our B2B SaaS platform. The role involves working closely with product managers and engineers to design dashboards, workflows, and collaboration tools. Your background seems like a great match.", time: "11:30am", date: "Monday, March 16" },
      { id: 5, sender: "me", text: "That sounds interesting. I\u2019ve been working on similar projects recently, particularly designing analytics dashboards and workflow-driven interfaces for SaaS platforms. I enjoy working closely with product teams to simplify complex systems for users.", time: "11:32am", date: "Monday, March 16" },
      { id: 6, sender: "them", text: "That\u2019s great to hear. We\u2019re building tools used by thousands of professionals daily, so creating intuitive and efficient interfaces is a top priority for us. Would you be open to a quick 20-30 minute conversation this week so I can share more details about the role and hear more about your experience?", time: "11:25am", date: "Monday, March 16" },
      { id: 7, sender: "me", text: "Yes, I\u2019d be happy to schedule a conversation. I\u2019m available later this week. Thursday afternoon or Friday morning would work well for me.", time: "11:27am", date: "Monday, March 16" },
      { id: 8, sender: "them", text: "Perfect. Let\u2019s schedule it for Thursday at 2:00 PM if that works for you. I\u2019ll send over a calendar invite shortly with the meeting link.", time: "10:02am", date: "Monday, March 16" },
    ],
  },
  {
    id: 2,
    name: "Alex Rivers",
    title: "CEO, TechFlow",
    avatar: null,
    avatarBg: "#6366F1",
    time: "1h ago",
    preview: "Thanks for the Demo yesterday, I have shared the details with my team and they have few questions...",
    labels: ["hot-lead"],
    unread: false,
    mailbox: "inbox",
    contact: { role: "CEO at TechFlow", location: "New York, USA", email: "alex@techflow.com", linkedin: "linkedin.com/in/alexrivers" },
    contactLabels: ["Hot Lead"],
    note: "",
    aiSummary: "Alex is interested in a demo follow-up. Team has questions about pricing.",
    messages: [
      { id: 1, sender: "them", text: "Thanks for the Demo yesterday, I have shared the details with my team and they have few questions about the implementation timeline.", time: "3:30pm", date: "Monday, March 16" },
    ],
  },
  {
    id: 3,
    name: "Michel Smith",
    title: "Founder of cloudScale",
    avatar: null,
    avatarBg: "#10B981",
    time: "6h ago",
    preview: "Let\u2019s connect next week to discuss potential partnership opportunities",
    labels: [],
    unread: false,
    mailbox: "inbox",
    contact: { role: "Founder at cloudScale", location: "London, UK", email: "michel@cloudscale.io", linkedin: "linkedin.com/in/michelsmith" },
    contactLabels: [],
    note: "",
    aiSummary: "",
    messages: [
      { id: 1, sender: "them", text: "Let\u2019s connect next week to discuss potential partnership opportunities", time: "9:00am", date: "Monday, March 16" },
    ],
  },
  {
    id: 4,
    name: "Sarah Chen",
    title: "Design Director at CreativeCo",
    avatar: null,
    avatarBg: "#EC4899",
    time: "12h ago",
    preview: "Let\u2019s schedule a call for next week thursday, does that work for you?",
    labels: [],
    unread: false,
    mailbox: "inbox",
    contact: { role: "Design Director at CreativeCo", location: "Austin, USA", email: "sarah@creativeco.com", linkedin: "linkedin.com/in/sarachen" },
    contactLabels: [],
    note: "",
    aiSummary: "",
    messages: [
      { id: 1, sender: "them", text: "Let\u2019s schedule a call for next week thursday, does that work for you?", time: "8:00am", date: "Monday, March 16" },
    ],
  },
  {
    id: 5,
    name: "Marcus Thorne",
    title: "Founder of Stealth AI",
    avatar: null,
    avatarBg: "#8B5CF6",
    time: "1d ago",
    preview: "Thanks for the Demo yesterday, I have shared the details with my team and they have few questions...",
    labels: ["partner"],
    unread: true,
    mailbox: "inbox",
    contact: { role: "Founder at Stealth AI", location: "Berlin, Germany", email: "marcus@stealthai.com", linkedin: "linkedin.com/in/marcusthorne" },
    contactLabels: ["Partner"],
    note: "",
    aiSummary: "Marcus wants to explore partnership opportunities around AI tooling.",
    messages: [
      { id: 1, sender: "them", text: "Thanks for the Demo yesterday, I have shared the details with my team and they have few questions about integration possibilities.", time: "2:00pm", date: "Sunday, March 15" },
    ],
  },
  {
    id: 6,
    name: "Elena Rodriguez",
    title: "Marketing Lead at ScaleUp",
    avatar: null,
    avatarBg: "#F43F5E",
    time: "3d ago",
    preview: "Thanks for the Demo yesterday, I have shared the details with my team and they have few...",
    labels: [],
    unread: true,
    mailbox: "inbox",
    contact: { role: "Marketing Lead at ScaleUp", location: "Miami, USA", email: "elena@scaleup.io", linkedin: "linkedin.com/in/elenarodriguez" },
    contactLabels: [],
    note: "",
    aiSummary: "",
    messages: [
      { id: 1, sender: "them", text: "Thanks for the Demo yesterday, I have shared the details with my team and they have few questions.", time: "11:00am", date: "Friday, March 13" },
    ],
  },
  {
    id: 7,
    name: "Green Leaf Community",
    title: "Tech Community",
    avatar: null,
    avatarBg: "#22C55E",
    time: "3d ago",
    preview: "Thanks for the Demo yesterday, I have shared the details with my team and they have few questions...",
    labels: ["community"],
    unread: true,
    mailbox: "inbox",
    contact: { role: "Tech Community", location: "Global", email: "info@greenleaf.community", linkedin: "linkedin.com/company/greenleaf" },
    contactLabels: ["Community"],
    note: "",
    aiSummary: "",
    messages: [
      { id: 1, sender: "them", text: "Thanks for the Demo yesterday, I have shared the details with my team and they have few questions about joining the community program.", time: "10:00am", date: "Friday, March 13" },
    ],
  },
  {
    id: 8,
    name: "Eleanor Davidson",
    title: "Product Design Lead, Interswitch",
    avatar: null,
    avatarBg: "#0EA5E9",
    time: "3d ago",
    preview: "Thanks for the Demo yesterday, I have shared the details with my team and they have few...",
    labels: [],
    unread: false,
    mailbox: "inbox",
    contact: { role: "Product Design Lead at Interswitch", location: "Lagos, Nigeria", email: "eleanor@interswitch.com", linkedin: "linkedin.com/in/eleanordavidson" },
    contactLabels: [],
    note: "",
    aiSummary: "",
    messages: [
      { id: 1, sender: "them", text: "Thanks for the Demo yesterday, I have shared the details with my team and they have few thoughts to share.", time: "9:30am", date: "Friday, March 13" },
    ],
  },
];
